### ISSUE TITLE
pnpm error when building 

### ISSUE THREAD

**Issue by HiiZun** [pkarpovich/vpn-exit-node#15]
Hello during the image build i get an error that come from PNPM

```
root@tail2vpn:~/vpn-exit-node# sudo docker compose up -d
[+] Building 90.2s (15/23)                                                                                                                       docker:default
 => [vpn-exit-node internal] load build definition from Dockerfile                                                                                         0.1s
 => => transferring dockerfile: 910B                                                                                                                       0.0s
 => [vpn-exit-node internal] load metadata for docker.io/tailscale/tailscale:stable                                                                        1.4s
 => [vpn-exit-node internal] load metadata for docker.io/library/node:lts-bullseye-slim                                                                    1.4s
 => [vpn-exit-node internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 109B                                                                                                                          0.0s
 => [vpn-exit-node pnpm 1/2] FROM docker.io/library/node:lts-bullseye-slim@sha256:c121fcd9656dde8ca373d1aa0b596f95af1764e0b7e6d4a212cbc78775c74c97        11.9s
 => => resolve docker.io/library/node:lts-bullseye-slim@sha256:c121fcd9656dde8ca373d1aa0b596f95af1764e0b7e6d4a212cbc78775c74c97                            0.1s
 => => sha256:e74e515ccdd11c20a37f85c8282405b69aa73ebaaff184a657b55bc88ab1c2eb 6.79kB / 6.79kB                                                             0.0s
 => => sha256:fa0650a893c25858ebb09921bc9b7824594e23405374a6adbcd3b4e27e28e3cf 31.43MB / 31.43MB                                                           1.3s
 => => sha256:094fc5e5eb8e80566becbd789518afee9c079116d1113e09b27827ab5ad8588d 4.07kB / 4.07kB                                                             0.6s
 => => sha256:bcb9bf7f2545c634a7bd557ee8d183add53ecc96107368fdd34e301703f1deb4 40.78MB / 40.78MB                                                           2.1s
 => => sha256:c121fcd9656dde8ca373d1aa0b596f95af1764e0b7e6d4a212cbc78775c74c97 3.94kB / 3.94kB                                                             0.0s
 => => sha256:02f66a728af1e59d9ecba2e2fbf48b2916eefa58afd6206244c0d5c9b8eb6474 1.93kB / 1.93kB                                                             0.0s
 => => sha256:2df65b02f59c33d59e3dd59dc4f5480cfcd6d6be0a0b4575cf5fb30eb9100d3d 1.74MB / 1.74MB                                                             1.9s
 => => sha256:2a00695bb87aba37d4682bc0257666b52ed56da7e5fb851898fd81f9ed1ad57b 448B / 448B                                                                 1.8s
 => => extracting sha256:fa0650a893c25858ebb09921bc9b7824594e23405374a6adbcd3b4e27e28e3cf                                                                  2.9s
 => => extracting sha256:094fc5e5eb8e80566becbd789518afee9c079116d1113e09b27827ab5ad8588d                                                                  0.0s
 => => extracting sha256:bcb9bf7f2545c634a7bd557ee8d183add53ecc96107368fdd34e301703f1deb4                                                                  5.2s
 => => extracting sha256:2df65b02f59c33d59e3dd59dc4f5480cfcd6d6be0a0b4575cf5fb30eb9100d3d                                                                  0.2s
 => => extracting sha256:2a00695bb87aba37d4682bc0257666b52ed56da7e5fb851898fd81f9ed1ad57b                                                                  0.0s
 => [vpn-exit-node internal] load build context                                                                                                            0.1s
 => => transferring context: 156.13kB                                                                                                                      0.0s
 => [vpn-exit-node stage-2 1/9] FROM docker.io/tailscale/tailscale:stable@sha256:a013ce5266e5c796efe31c7cf9562deb21423f8586361d7faadaf675fa4296ac         12.0s
 => => resolve docker.io/tailscale/tailscale:stable@sha256:a013ce5266e5c796efe31c7cf9562deb21423f8586361d7faadaf675fa4296ac                                0.1s
 => => sha256:a013ce5266e5c796efe31c7cf9562deb21423f8586361d7faadaf675fa4296ac 906B / 906B                                                                 0.0s
 => => sha256:2936ec795309dab9418967409c0ed68907d5ebe6542adc41a88d9a39243cecee 722B / 722B                                                                 0.0s
 => => sha256:6d9e82e8e83d522bdbe408084de78ed746d0df88bc52edde3b29a2031a66e2b8 905B / 905B                                                                 0.0s
 => => sha256:1cc3d825d8b2468ef662a8b631220516f492e24232477209fe863836d2d2ed44 3.42MB / 3.42MB                                                             5.5s
 => => sha256:904e11e45590e48a54a13e96beb200b2fd511826bb3899082ca26125907ddba0 2.55MB / 2.55MB                                                             5.0s
 => => sha256:42f8f851a62102157ac80eb62086368b09e8bc4e9089079547b7387fbc9e12a0 41.14MB / 41.14MB                                                           7.6s
 => => extracting sha256:1cc3d825d8b2468ef662a8b631220516f492e24232477209fe863836d2d2ed44                                                                  0.3s
 => => extracting sha256:904e11e45590e48a54a13e96beb200b2fd511826bb3899082ca26125907ddba0                                                                  0.3s
 => => extracting sha256:42f8f851a62102157ac80eb62086368b09e8bc4e9089079547b7387fbc9e12a0                                                                  4.0s
 => [vpn-exit-node pnpm 2/2] RUN corepack enable && corepack prepare pnpm@7.18.2 --activate                                                                4.6s
 => [vpn-exit-node stage-2 2/9] WORKDIR /usr/app                                                                                                           0.4s
 => [vpn-exit-node stage-2 3/9] RUN apk update &&  apk add -U dumb-init nodejs openvpn                                                                     4.2s
 => [vpn-exit-node builder 1/7] WORKDIR /usr/app                                                                                                           0.1s
 => [vpn-exit-node builder 2/7] COPY pnpm-lock.yaml ./                                                                                                     0.1s
 => [vpn-exit-node stage-2 4/9] RUN apk add --no-cache ca-certificates iptables iproute2 ip6tables                                                         1.2s
 => ERROR [vpn-exit-node builder 3/7] RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store     pnpm fetch                                        71.9s 
 => [vpn-exit-node stage-2 5/9] COPY package.json ./                                                                                                       0.1s 
------                                                                                                                                                          
 > [vpn-exit-node builder 3/7] RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store     pnpm fetch:                                                    
1.459 Importing packages to virtual store
1.508 Already up to date
1.552 Progress: resolved 1, reused 0, downloaded 0, added 0
1.822  WARN  GET https://registry.npmjs.org/@changesets/cli/-/cli-2.25.2.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.822  WARN  GET https://registry.npmjs.org/@babel/runtime/-/runtime-7.20.6.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.834  WARN  GET https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.835  WARN  GET https://registry.npmjs.org/@changesets/apply-release-plan/-/apply-release-plan-6.1.2.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.842  WARN  GET https://registry.npmjs.org/@changesets/config/-/config-2.2.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.844  WARN  GET https://registry.npmjs.org/@changesets/errors/-/errors-0.1.4.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.844  WARN  GET https://registry.npmjs.org/extendable-error/-/extendable-error-0.1.7.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.845  WARN  GET https://registry.npmjs.org/@changesets/get-dependents-graph/-/get-dependents-graph-1.3.4.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.847  WARN  GET https://registry.npmjs.org/@changesets/types/-/types-5.2.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.848  WARN  GET https://registry.npmjs.org/@manypkg/get-packages/-/get-packages-1.1.3.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.848  WARN  GET https://registry.npmjs.org/@changesets/types/-/types-4.1.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.849  WARN  GET https://registry.npmjs.org/@manypkg/find-root/-/find-root-1.1.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.850  WARN  GET https://registry.npmjs.org/@types/node/-/node-12.20.55.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.851  WARN  GET https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.852  WARN  GET https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
1.853  WARN  GET https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
2.555 Progress: resolved 519, reused 0, downloaded 0, added 0
11.81  WARN  GET https://registry.npmjs.org/@changesets/cli/-/cli-2.25.2.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.82  WARN  GET https://registry.npmjs.org/@babel/runtime/-/runtime-7.20.6.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.83  WARN  GET https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.83  WARN  GET https://registry.npmjs.org/@changesets/apply-release-plan/-/apply-release-plan-6.1.2.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.84  WARN  GET https://registry.npmjs.org/@changesets/config/-/config-2.2.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@changesets/errors/-/errors-0.1.4.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/extendable-error/-/extendable-error-0.1.7.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@changesets/get-dependents-graph/-/get-dependents-graph-1.3.4.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@changesets/types/-/types-5.2.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@manypkg/get-packages/-/get-packages-1.1.3.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@changesets/types/-/types-4.1.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@manypkg/find-root/-/find-root-1.1.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/@types/node/-/node-12.20.55.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/find-up/-/find-up-4.1.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/locate-path/-/locate-path-5.0.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
11.85  WARN  GET https://registry.npmjs.org/p-locate/-/p-locate-4.1.0.tgz error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
71.82  WARN  GET https://registry.npmjs.org/p-limit/-/p-limit-2.3.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
71.82  ERR_INVALID_THIS  Value of "this" must be of type URLSearchParams
71.82 
71.82 pnpm [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
71.82     at Proxy.getAll (node:internal/url:535:13)
71.82     at Proxy.<anonymous> (/root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:58802:55)
71.82     at /root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:58855:31
71.82     at Array.reduce (<anonymous>)
71.82     at Proxy.raw (/root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:58854:33)
71.82     at new Headers (/root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:58748:28)
71.82     at getNodeRequestOptions (/root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:59067:23)
71.82     at /root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:59124:25
71.82     at new Promise (<anonymous>)
71.82     at fetch (/root/.cache/node/corepack/v1/pnpm/7.18.2/dist/pnpm.cjs:59122:14)
71.82  WARN  GET https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
------
failed to solve: process "/bin/sh -c pnpm fetch" did not complete successfully: exit code: 1
```

any help appreciated
Thanks 👌

**Comment by pkarpovich** [comment]
Thanks for the report. The `ERR_INVALID_THIS` failures came from the old `pnpm@7.18.2` step in the Dockerfile (a known pnpm/Node incompatibility on newer Node).

That build path is gone now: `main` was rewritten into a pure docker-compose appliance built from off-the-shelf images (`tailscale/tailscale`, optional `gluetun`, a SOCKS5 proxy) - no Dockerfile, no Node, no `pnpm`, so there's nothing left to build or fetch and this error can't happen.

To use it now: pull `main` and follow the README quick start (`make up-exit` / `up-socks` / `up-vpn`). The old Node version is preserved at tag `v1.0.2`.

Closing as resolved by the rewrite - reopen if you hit anything on the new setup.
